name: Build and Deploy to Lightsail

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: ap-southeast-1
  AWS_LIGHTSAIL_SERVICE_NAME: gic-hack-1

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install Amazon Client
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install || true
        aws --version
        curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
        sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
        sudo chmod +x /usr/local/bin/lightsailctl

    - name: Log in to AWS Lightsail with Secrets
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
      
    - name: Docker build
      run: docker buildx build --platform linux/amd64 -t gic-hack-2 .

    - name: Upload image to AWS container register
      run: |
        aws lightsail push-container-image \
          --region ${{ env.AWS_REGION }} \
          --service-name gic-hack-2 \
          --label gic-hack-2 \
          --image gic-hack-2:latest
